-- Feedback utilisateur — voir js/feedback.js (formulaire, icône d'entête)
-- et js/admin.js (onglet "Avis" de la modale admin, lecture seule
-- admin). CONTRAIREMENT à admin_config (migration 018, où la séparation
-- admin est juste un choix d'affichage côté client — chacun n'y voit de
-- toute façon que sa propre ligne), un retour peut contenir une remarque
-- personnelle qu'un autre compte ne doit JAMAIS pouvoir lire, même via un
-- appel API direct : la restriction à l'admin doit être une vraie règle
-- RLS ici, pas un simple masquage dans l'interface.
--
-- ADMIN_EMAIL dupliqué depuis js/admin.js (une policy RLS ne peut pas
-- lire une constante JS) — à garder synchronisé si jamais le compte admin
-- change un jour.
create table public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('bug', 'idee', 'autre')),
  message text not null,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

-- Chacun peut envoyer un retour et relire les siens (pas les modifier ni
-- les supprimer une fois envoyés — une boîte à idées, pas un brouillon).
create policy "Users can insert own feedback"
  on public.feedback for insert
  with check (auth.uid() = user_id);

create policy "Users can view own feedback"
  on public.feedback for select
  using (auth.uid() = user_id);

-- Policies SELECT/UPDATE multiples sur la même table = combinées en OR
-- par Postgres : un utilisateur voit les siens (policy ci-dessus) OU
-- l'admin voit tout (celle-ci) — jamais l'inverse (un utilisateur ne voit
-- jamais les retours d'un autre utilisateur).
create policy "Admin can view all feedback"
  on public.feedback for select
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

create policy "Admin can update feedback"
  on public.feedback for update
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');
