-- Journal d'événements + stats admin — voir js/logging.js (capture) et
-- js/admin.js (affichage, onglet "Stats & logs"). Table d'ajout seul
-- (append-only), volontairement générique (event_type + detail texte
-- libre) plutôt qu'une table par type d'événement : signup, installation
-- PWA, erreur JS non interceptée — un nouveau type de log demain n'exige
-- pas de nouvelle migration, juste une nouvelle valeur de event_type.
--
-- INSERT ouvert à `anon` ET `authenticated` (pas juste authenticated,
-- contrairement à toutes les autres tables du projet) : une erreur JS
-- peut survenir sur l'écran de connexion ou le profil public, AVANT toute
-- session — un visiteur jamais connecté doit quand même pouvoir logger un
-- crash. Compromis assumé pour un usage perso (n'importe qui pourrait en
-- théorie spammer des lignes bidon) : même famille de choix que
-- site_status/admin_config, pas une vraie séparation de rôle pour l'écriture
-- — mais la LECTURE, elle, est une vraie policy RLS (comme feedback,
-- migrations/026) : personne d'autre que l'admin ne voit ce journal.
create table public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  detail text,
  created_at timestamptz not null default now()
);

alter table public.app_events enable row level security;

create policy "Anyone can log an event"
  on public.app_events for insert
  to anon, authenticated
  with check (true);

create policy "Admin can view all events"
  on public.app_events for select
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

-- Compteurs globaux ("Activité globale" de l'onglet admin) — SECURITY
-- DEFINER comme get_global_top_films (migrations/015) : lit `films`/
-- `tv_shows`/`viewings`/auth.users de TOUT LE MONDE en interne (RLS
-- contournée volontairement) mais ne renvoie que 4 nombres, jamais une
-- ligne individuelle — aucune fuite possible de qui a fait quoi.
create or replace function public.get_admin_site_stats()
returns table(
  total_users bigint,
  total_films bigint,
  total_series bigint,
  total_viewings bigint
)
language sql
security definer
set search_path = public
stable
as $$
  select
    (select count(*) from auth.users) as total_users,
    (select count(*) from public.films) as total_films,
    (select count(*) from public.tv_shows) as total_series,
    (select count(*) from public.viewings) as total_viewings;
$$;

revoke all on function public.get_admin_site_stats() from public;
grant execute on function public.get_admin_site_stats() to authenticated;
