-- Nouveautés (v2.1+) : courtes annonces des mises à jour, affichées une
-- fois à la connexion (modale automatique + badge, comme le "quoi de neuf"
-- d'autres apps) puis consultables à tout moment via l'icône dédiée de
-- l'entête (mégaphone) — voir js/changelog.js. Rédigées et publiées depuis
-- l'onglet "Nouveautés" de la modale admin (js/admin.js).
--
-- Vraie policy RLS ici (comme feedback, migrations/026), PAS un simple
-- garde-fou d'affichage façon admin_config : ce contenu doit être lisible
-- par TOUS les utilisateurs connectés une fois publié, pas seulement
-- l'admin. Brouillon (published = false) : réservé à l'admin le temps de
-- la rédaction, avant de dire "on publie" — voir published_at, rempli
-- seulement au moment de la publication (pas à la création), pour trier
-- par vraie date de mise en ligne plutôt que de rédaction.
create table public.changelog_entries (
  id bigint generated by default as identity primary key,
  version text not null,
  title text not null,
  body text not null,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.changelog_entries enable row level security;

create policy "Anyone can view published changelog entries"
  on public.changelog_entries for select
  using (published = true);

-- L'admin voit aussi ses brouillons non encore publiés, pour les relire
-- avant de publier — sans policy à part, "Anyone can view published..."
-- ci-dessus ne les couvrirait pas.
create policy "Admin can view all changelog entries"
  on public.changelog_entries for select
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

create policy "Admin can insert changelog entries"
  on public.changelog_entries for insert
  with check ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

create policy "Admin can update changelog entries"
  on public.changelog_entries for update
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

create policy "Admin can delete changelog entries"
  on public.changelog_entries for delete
  using ((auth.jwt() ->> 'email') = 'sab.fxs@gmail.com');

-- Badge "vu" : nouvelle colonne sur user_activity_state (migrations/023),
-- même table que last_seen_amis/last_seen_groupes plutôt qu'une table à
-- part pour une seule colonne de plus — voir loadActivityState() dans
-- js/activityState.js (mise à jour pour la seeder à la création de ligne,
-- même logique que les deux autres : un compte tout neuf ne doit pas voir
-- l'historique déjà publié comme "non lu").
alter table public.user_activity_state
  add column last_seen_changelog timestamptz;
