-- Fiche film (v2.1, retour utilisateur) — voir js/filmDetail.js. Cliquer
-- sur un film n'importe où dans l'app (profil d'un ami, Top, groupes...)
-- ouvre désormais une vraie page dédiée : résumé, genre, note moyenne
-- communautaire, + noter/aimer/commenter, plutôt que la seule note posée
-- à côté du titre.
--
-- Un film est identifié par son tmdb_id (comme get_global_top_films,
-- migrations/015) : pas de table "films canoniques" séparée à maintenir,
-- like/commentaire s'accrochent directement à l'id numérique TMDB.

-- --- Like (v2.1) --- Distinct du ★ favori (personnel, jamais vu des
-- autres) : un like ici est un vrai signal social, visible des amis.
create table public.film_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tmdb_id integer not null,
  created_at timestamptz not null default now(),
  unique (user_id, tmdb_id)
);

-- --- Commentaire (v2.1) --- Distinct de `films.review` (personnel) : un
-- commentaire ici est public (entre amis), plusieurs personnes peuvent en
-- laisser un sur le même film — même principe que
-- group_proposal_comments (migrations/012), à l'échelle d'un film plutôt
-- que d'une proposition de groupe.
create table public.film_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tmdb_id integer not null,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.film_likes enable row level security;
alter table public.film_comments enable row level security;

-- Vérifie l'amitié en contournant RLS pour sa propre requête interne —
-- même pattern que is_group_member (migrations/013), pour éviter toute
-- récursion de policy et pouvoir être appelée directement depuis une
-- USING clause.
create or replace function public.are_friends(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select p_user_a = p_user_b or exists (
    select 1 from public.friendships
    where status = 'accepted'
      and ((requester_id = p_user_a and addressee_id = p_user_b)
        or (requester_id = p_user_b and addressee_id = p_user_a))
  );
$$;

revoke all on function public.are_friends(uuid, uuid) from public;
grant execute on function public.are_friends(uuid, uuid) to authenticated;

create policy "Users can view own or friends' likes"
  on public.film_likes for select
  using (public.are_friends(auth.uid(), user_id));

create policy "Users can like as themselves"
  on public.film_likes for insert
  with check (auth.uid() = user_id);

create policy "Users can unlike their own like"
  on public.film_likes for delete
  using (auth.uid() = user_id);

create policy "Users can view own or friends' comments"
  on public.film_comments for select
  using (public.are_friends(auth.uid(), user_id));

create policy "Users can comment as themselves"
  on public.film_comments for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own comment"
  on public.film_comments for delete
  using (auth.uid() = user_id);

-- --- Note moyenne communautaire (v2.1) --- Même formule que
-- get_global_top_films (migrations/015), restreinte à un seul tmdb_id
-- plutôt qu'un classement — n'expose que l'agrégat (moyenne + nombre de
-- votants), jamais une ligne individuelle, même principe que le top.
create or replace function public.get_film_stats(p_tmdb_id integer)
returns table(avg_note numeric, rating_count integer)
language sql
security definer
set search_path = public
stable
as $$
  select
    round(avg(coalesce(f.manual_note, (
      select round(avg(v.value::numeric) * 10) / 2
      from jsonb_each_text(f.crit) as v
    ))), 2) as avg_note,
    count(*)::integer as rating_count
  from public.films f
  where f.tmdb_id = p_tmdb_id;
$$;

revoke all on function public.get_film_stats(integer) from public;
grant execute on function public.get_film_stats(integer) to authenticated;
